import React from 'react';
import './ClassGuides.css';

const LichborneGuide = () => {
  return (
    <div className="class-guide">
      <h2>Lichborne Guide</h2>
      <p className="class-subtitle">Undeath Aspirant • Soul Manipulator • Immortality Seeker</p>

      <section className="guide-section">
        <h3>Class Overview</h3>
        <p>
          The <strong>Lichborne</strong> is a necromancer who has begun the transformation into a lich—a powerful undead spellcaster.
          Unlike traditional necromancers who merely control the dead, Lichborne have undergone rituals to anchor their souls to phylacteries,
          granting them aspects of undeath while still retaining their mortality.
        </p>
        <p>
          In a party, Lichborne serve as powerful spellcasters with unique defensive capabilities and access to both necromantic and arcane magic.
          Their partial undead nature gives them resistances to effects that target the living, while their phylactery provides a failsafe against death.
        </p>
      </section>

      <section className="guide-section">
        <h3>Unique Mechanic – Phylactery Core System</h3>
        <p>
          The Lichborne's signature mechanic is the Phylactery Core System—a complex interplay between their physical form and the soul container
          they've created. The phylactery stores Essence Echoes, a resource that powers their most potent abilities and provides protection against death.
        </p>
        
        <div className="mechanic-details">
          <h4>Key Phylactery Concepts:</h4>
          <ul className="mechanic-list">
            <li><strong>Essence Echoes:</strong> A resource generated by absorbing life force from dying creatures or sacrificing your own vitality.</li>
            <li><strong>Maximum Echoes:</strong> Your phylactery can store Echoes equal to your Intelligence + your level.</li>
            <li><strong>Spending Echoes:</strong> Echoes can be spent to fuel powerful necromantic abilities or to resist death.</li>
            <li><strong>Death Resistance:</strong> When you would die, you can spend Echoes to remain at 1 HP instead.</li>
            <li><strong>Phylactery Bond:</strong> The strength of your connection to your phylactery determines which undead traits you manifest.</li>
            <li><strong>Decay:</strong> If your phylactery is empty of Echoes for too long, you begin to experience negative effects of incomplete transformation.</li>
          </ul>
        </div>

        <div className="ability-table">
          <h4>Phylactery Bond Levels:</h4>
          <table>
            <thead>
              <tr>
                <th>Bond Level</th>
                <th>Echoes Required</th>
                <th>Undead Traits Gained</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Nascent</td>
                <td>1-5 Echoes</td>
                <td>Resistance to disease, reduced need for sleep</td>
              </tr>
              <tr>
                <td>Developing</td>
                <td>6-10 Echoes</td>
                <td>Immunity to disease, no need for food or water</td>
              </tr>
              <tr>
                <td>Established</td>
                <td>11-15 Echoes</td>
                <td>Resistance to necrotic damage, immunity to poison</td>
              </tr>
              <tr>
                <td>Ascendant</td>
                <td>16-20 Echoes</td>
                <td>Immunity to necrotic damage, resistance to cold, no need to breathe</td>
              </tr>
              <tr>
                <td>Transcendent</td>
                <td>21+ Echoes</td>
                <td>Resistance to non-magical physical damage, immunity to exhaustion</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="note-box">
          <strong>Tactical Tip:</strong> The key to mastering the Lichborne is balancing Essence Echo generation and consumption.
          Maintain enough Echoes to keep your desired Bond Level active, but don't hesitate to spend them on powerful abilities when needed.
          Remember that your phylactery is both your greatest strength and your greatest vulnerability—protect it at all costs.
        </p>
      </section>

      <section className="guide-section">
        <h3>Talent Trees</h3>
        <p>
          Lichborne have three distinct talent trees that emphasize different aspects of their transformation and powers.
          Each tree offers a unique playstyle and approach to undeath.
        </p>

        <div className="talent-tree">
          <h4>1. Phylactery Sovereign</h4>
          <p><em>Focus on strengthening your phylactery and maximizing your undead transformation.</em></p>
          <ul>
            <li><strong>Reinforced Phylactery:</strong> Your phylactery can store additional Essence Echoes.</li>
            <li><strong>Soul Siphon:</strong> Gain Essence Echoes whenever a creature dies within 30 feet of you.</li>
            <li><strong>Undying Resilience:</strong> Spend Essence Echoes to gain temporary immunity to specific damage types.</li>
            <li><strong>Lichform (capstone):</strong> Temporarily transform into a true lich for 1d4 rounds, gaining all undead immunities and access to powerful necromantic abilities.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree is ideal for players who want to maximize their undead traits and defensive capabilities. You'll be incredibly durable and difficult to kill.</p>
        </div>

        <div className="talent-tree">
          <h4>2. Arcane Wretch</h4>
          <p><em>Emphasize necromantic spellcasting and soul manipulation.</em></p>
          <ul>
            <li><strong>Soul Harvest:</strong> Extract additional Essence Echoes from dying creatures.</li>
            <li><strong>Necrotic Mastery:</strong> Your necromantic spells deal additional damage and can critical hit.</li>
            <li><strong>Death Pact:</strong> Form a bond with a creature that transfers damage you take to them instead.</li>
            <li><strong>Soul Rend (capstone):</strong> Tear the soul from a living target, instantly killing them if they fail a save and converting their life force into massive Essence Echoes.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree focuses on offensive necromantic magic and soul manipulation. You'll excel at dealing damage and controlling the battlefield through fear and death effects.</p>
        </div>

        <div className="talent-tree">
          <h4>3. Dread Reclaimer</h4>
          <p><em>Master the raising and control of undead minions.</em></p>
          <ul>
            <li><strong>Undead Mastery:</strong> Control more undead simultaneously and enhance their capabilities.</li>
            <li><strong>Essence Transfer:</strong> Channel Essence Echoes into your undead minions to empower them.</li>
            <li><strong>Death Knight:</strong> Transform a powerful slain warrior into a special undead champion that serves you.</li>
            <li><strong>Army of the Dead (capstone):</strong> Spend all your Essence Echoes to raise every corpse within 100 feet as undead under your control for 1d4 rounds.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree is for players who want to command an undead army. You'll control multiple minions that can overwhelm enemies with numbers and versatility.</p>
        </div>
      </section>

      <section className="guide-section">
        <h3>Attribute Priorities</h3>
        <div className="attribute-table">
          <table>
            <thead>
              <tr>
                <th>Attribute</th>
                <th>Importance</th>
                <th>Effect</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Intelligence</strong></td>
                <td>Primary</td>
                <td>Increases spell effectiveness, maximum Essence Echoes, and necromantic control</td>
              </tr>
              <tr>
                <td><strong>Constitution</strong></td>
                <td>Secondary</td>
                <td>Improves survivability during the vulnerable stages of transformation</td>
              </tr>
              <tr>
                <td><strong>Wisdom</strong></td>
                <td>Secondary</td>
                <td>Enhances your perception of souls and resistance to mental effects</td>
              </tr>
              <tr>
                <td><strong>Charisma</strong></td>
                <td>Tertiary</td>
                <td>Useful for commanding undead and intimidation</td>
              </tr>
              <tr>
                <td><strong>Dexterity</strong></td>
                <td>Tertiary</td>
                <td>Provides some defensive capability</td>
              </tr>
              <tr>
                <td><strong>Strength</strong></td>
                <td>Dump Stat</td>
                <td>Minimal benefit for Lichborne</td>
              </tr>
              <tr>
                <td><strong>Lichcraft</strong> (Special)</td>
                <td>Primary</td>
                <td>A unique attribute that enhances undead traits and phylactery capabilities</td>
              </tr>
              <tr>
                <td><strong>Arcane Decay</strong> (Special)</td>
                <td>Secondary</td>
                <td>A unique attribute that determines how much of your humanity you've sacrificed</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="guide-section">
        <h3>Core Abilities & Tactics</h3>
        
        <h4>Essential Abilities:</h4>
        <ul className="ability-list">
          <li><strong>Soul Drain:</strong> Extract Essence Echoes from a living target, dealing necrotic damage.</li>
          <li><strong>Phylactery Shield:</strong> Spend Essence Echoes to create a protective barrier that absorbs damage.</li>
          <li><strong>Necrotic Bolt:</strong> Deal necrotic damage to a target and gain Essence Echoes if they die within 3 rounds.</li>
          <li><strong>Raise Dead:</strong> Create an undead minion from a corpse that obeys your commands.</li>
          <li><strong>Death Ward:</strong> Spend Essence Echoes to prevent death, remaining at 1 HP instead of falling unconscious.</li>
        </ul>

        <h4>Combat Strategy:</h4>
        <p>The Lichborne's approach to combat balances Echo management with offensive spellcasting:</p>
        <ol className="round-flow">
          <li><strong>Preparation Phase:</strong> Ensure your phylactery has sufficient Echoes to maintain your desired Bond Level.</li>
          <li><strong>Control Phase:</strong> Use necromantic spells to control the battlefield and generate additional Echoes.</li>
          <li><strong>Adaptation Phase:</strong> Adjust your strategy based on Echo levels—conserve when low, spend aggressively when high.</li>
          <li><strong>Transcendence Phase:</strong> When Echoes are abundant, use powerful abilities that consume large amounts to turn the tide of battle.</li>
        </ol>

        <div className="note-box">
          <h4>Advanced Tactics:</h4>
          <ul>
            <li>Use dice or tokens to track your current Essence Echoes.</li>
            <li>Always keep a minimum reserve of Echoes for Death Ward in case you're critically injured.</li>
            <li>Remember that your phylactery is vulnerable—keep its physical location secret and well-protected.</li>
            <li>Coordinate with party members to ensure you can safely harvest Echoes from fallen enemies.</li>
            <li>Be mindful of how your undead nature might affect social interactions—some NPCs may react with fear or hostility.</li>
          </ul>
        </div>
      </section>

      <section className="guide-section">
        <h3>Sample Combat Round-Flow</h3>
        <p>Here's how a typical combat encounter might play out for a Lichborne:</p>
        
        <div className="round-flow">
          <ol>
            <li>
              <strong>Round 1:</strong> Cast Raise Dead on a nearby corpse to create an undead minion, then position it to protect you.
              <em>Essence Echoes: 12 (Established Bond)</em>
            </li>
            <li>
              <strong>Round 2:</strong> Cast Soul Drain on the strongest enemy, dealing 2d8 necrotic damage and gaining 2 Essence Echoes.
              <em>Essence Echoes: 14 (Established Bond)</em>
            </li>
            <li>
              <strong>Round 3:</strong> Cast Necrotic Bolt at a weakened enemy, dealing 3d6 necrotic damage and potentially gaining more Echoes if they die.
              <em>Essence Echoes: 15 (Established Bond)</em>
            </li>
            <li>
              <strong>Round 4:</strong> A powerful enemy targets you with a critical hit. Spend 5 Essence Echoes to activate Phylactery Shield, reducing the damage by half.
              <em>Essence Echoes: 10 (Developing Bond)</em>
            </li>
            <li>
              <strong>Round 5:</strong> With the battle turning against you, spend 8 Essence Echoes to cast a powerful necromantic spell that deals 8d6 necrotic damage to all enemies in a 20-foot radius.
              <em>Essence Echoes: 2 (Nascent Bond)</em>
            </li>
          </ol>
        </div>

        <p className="conclusion">
          The Lichborne thrives on <strong>the balance between life and undeath</strong>—drawing power from souls while gradually transcending mortality.
          Master the flow of Essence Echoes, and you'll walk the path to true lichdom, becoming an immortal master of death magic.
        </p>
      </section>
    </div>
  );
};

export default LichborneGuide;
