import React from 'react';
import './ClassGuides.css';

const MartyrGuide = () => {
  return (
    <div className="class-guide">
      <h2>Martyr Guide</h2>
      <p className="class-subtitle">Sacrificial Healer • Pain Channeler • Blood Mage</p>

      <section className="guide-section">
        <h3>Class Overview</h3>
        <p>
          The <strong>Martyr</strong> is a unique support class that channels their own life force to heal, protect, and empower allies.
          Unlike traditional healers who draw power from external sources, Martyrs use their own blood and pain as a resource,
          making them powerful but inherently risky to play.
        </p>
        <p>
          In a party, Martyrs serve as primary healers and support characters who can provide extraordinary benefits at the cost of their own health.
          Their self-sacrificing playstyle creates dramatic moments where they must balance their own survival against the needs of the group.
        </p>
      </section>

      <section className="guide-section">
        <h3>Unique Mechanic – Blood Thresholds and Pain Charges</h3>
        <p>
          The Martyr's unique system turns every wound into a resource. By sacrificing HP (often as a cost for abilities),
          the Martyr builds up Conviction Points, Blood Vows, or Pain Charges that fuel special effects.
        </p>
        
        <div className="mechanic-details">
          <h4>Key Blood Mechanics:</h4>
          <ul className="mechanic-list">
            <li><strong>Pain Charges:</strong> The Martyr gains 1 Pain Charge per 5% of maximum HP lost, stacking to grant bonuses at each threshold (e.g., +1 attack/damage per charge).</li>
            <li><strong>Blood Vows:</strong> The Martyr swears an oath (at an HP cost) and then accumulates "sacrifice" until the vow completes, triggering a dramatic payoff.</li>
            <li><strong>Conviction Points:</strong> A resource generated by taking damage or sacrificing health that can be spent to enhance abilities.</li>
            <li><strong>Stigmata:</strong> Persistent wounds that drain health but provide ongoing benefits to allies.</li>
            <li><strong>Martyrdom:</strong> Ultimate abilities that can save a party at the cost of potentially fatal damage to the Martyr.</li>
          </ul>
        </div>

        <div className="ability-table">
          <h4>Pain Charge Thresholds:</h4>
          <table>
            <thead>
              <tr>
                <th>Charges</th>
                <th>Threshold Name</th>
                <th>Effects</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1-2</td>
                <td>Suffering</td>
                <td>+1 to healing spells per charge, minor pain resistance</td>
              </tr>
              <tr>
                <td>3-4</td>
                <td>Agony</td>
                <td>+2 to healing spells per charge, 25% pain resistance, healing aura (1d4 HP to allies within 10 ft per round)</td>
              </tr>
              <tr>
                <td>5-6</td>
                <td>Torment</td>
                <td>+3 to healing spells per charge, 50% pain resistance, healing aura (1d6 HP), damage reflection (25% of damage taken)</td>
              </tr>
              <tr>
                <td>7+</td>
                <td>Martyrdom</td>
                <td>+4 to healing spells per charge, 75% pain resistance, healing aura (1d8 HP), damage reflection (50%), access to ultimate abilities</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="note-box">
          <strong>Tactical Tip:</strong> The key to mastering the Martyr is finding the balance between sacrifice and survival.
          Accumulate Pain Charges strategically, using healing abilities on yourself when necessary to avoid death.
          Remember that you can't help your allies if you're dead—don't sacrifice too much too quickly unless it's truly a desperate situation.
        </p>
      </section>

      <section className="guide-section">
        <h3>Talent Trees</h3>
        <p>
          Martyrs have three distinct talent trees that emphasize different aspects of self-sacrifice.
          Each tree offers a unique playstyle and approach to supporting the party.
        </p>

        <div className="talent-tree">
          <h4>1. Redemption</h4>
          <p><em>Focus on healing and protection through personal sacrifice.</em></p>
          <ul>
            <li><strong>Blood Offering:</strong> Sacrifice your own HP to heal allies for a greater amount.</li>
            <li><strong>Shared Pain:</strong> Take a portion of damage that would be dealt to an ally.</li>
            <li><strong>Stigmata:</strong> Create persistent wounds on yourself that continuously heal nearby allies.</li>
            <li><strong>Divine Intervention (capstone):</strong> Sacrifice half your maximum HP to prevent all allies from dropping below 1 HP for 1d4 rounds.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree is ideal for players who want to focus on keeping the party alive at all costs. You'll excel at healing and damage prevention, though at significant personal risk.</p>
        </div>

        <div className="talent-tree">
          <h4>2. Flagellation</h4>
          <p><em>Channel pain into offensive power and battlefield control.</em></p>
          <ul>
            <li><strong>Pain to Power:</strong> Convert damage taken into bonus damage on your next attack.</li>
            <li><strong>Blood Magic:</strong> Cast spells using HP instead of mana, with increased effectiveness.</li>
            <li><strong>Crimson Lash:</strong> Create weapons from your own blood that deal additional damage based on your Pain Charges.</li>
            <li><strong>Bloodstorm (capstone):</strong> Sacrifice 75% of your current HP to deal massive damage to all enemies in a large area.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree is for players who want to turn their suffering into offensive capability. You'll deal significant damage while still maintaining some support abilities.</p>
        </div>

        <div className="talent-tree">
          <h4>3. Judgment</h4>
          <p><em>Focus on retribution, reflecting damage back to attackers.</em></p>
          <ul>
            <li><strong>Retribution:</strong> When damaged, automatically deal a portion of that damage back to the attacker.</li>
            <li><strong>Blood Oath:</strong> Mark an enemy with a vow of vengeance. Any damage you take from them is reflected back doubled.</li>
            <li><strong>Sacrificial Bond:</strong> Link yourself to an enemy so that they take a portion of all damage dealt to you by any source.</li>
            <li><strong>Divine Vengeance (capstone):</strong> For 1d4 rounds, all damage dealt to you is fully reflected back to attackers while healing nearby allies.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree focuses on turning the Martyr's suffering into a weapon against enemies. You'll punish attackers for targeting you while still providing support to allies.</p>
        </div>
      </section>

      <section className="guide-section">
        <h3>Attribute Priorities</h3>
        <div className="attribute-table">
          <table>
            <thead>
              <tr>
                <th>Attribute</th>
                <th>Importance</th>
                <th>Effect</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Constitution</strong></td>
                <td>Primary</td>
                <td>Increases HP pool for sacrifices and improves survival</td>
              </tr>
              <tr>
                <td><strong>Spirit</strong></td>
                <td>Primary</td>
                <td>Enhances healing abilities and pain threshold</td>
              </tr>
              <tr>
                <td><strong>Charisma</strong></td>
                <td>Secondary</td>
                <td>Improves the effectiveness of vows and conviction-based abilities</td>
              </tr>
              <tr>
                <td><strong>Wisdom</strong></td>
                <td>Secondary</td>
                <td>Helps with managing resources and timing sacrifices</td>
              </tr>
              <tr>
                <td><strong>Dexterity</strong></td>
                <td>Tertiary</td>
                <td>Provides some defensive capability</td>
              </tr>
              <tr>
                <td><strong>Strength</strong></td>
                <td>Dump Stat</td>
                <td>Minimal benefit for Martyrs unless using Flagellation tree</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="guide-section">
        <h3>Core Abilities & Tactics</h3>
        
        <h4>Essential Abilities:</h4>
        <ul className="ability-list">
          <li><strong>Blood Sacrifice:</strong> Sacrifice a portion of your HP to heal an ally for a greater amount.</li>
          <li><strong>Pain Transfer:</strong> Take damage that would be dealt to an ally onto yourself instead.</li>
          <li><strong>Stigmata:</strong> Create wounds on yourself that continuously heal nearby allies.</li>
          <li><strong>Blood Vow:</strong> Swear an oath against an enemy, gaining power as you take damage from them.</li>
          <li><strong>Martyr's Blessing:</strong> Convert Pain Charges into powerful buffs for allies.</li>
        </ul>

        <h4>Combat Strategy:</h4>
        <p>The Martyr's approach to combat revolves around strategic sacrifice and resource management:</p>
        <ol className="round-flow">
          <li><strong>Opening Phase:</strong> Use minor sacrifices to build initial Pain Charges while assessing the battlefield.</li>
          <li><strong>Support Phase:</strong> Use Blood Sacrifice and Pain Transfer to keep allies healthy while accumulating more Pain Charges.</li>
          <li><strong>Threshold Phase:</strong> Once you reach higher Pain Charge thresholds, leverage your enhanced abilities and auras.</li>
          <li><strong>Crisis Phase:</strong> In desperate situations, use ultimate abilities that sacrifice large portions of your health for game-changing effects.</li>
        </ol>

        <div className="note-box">
          <h4>Advanced Tactics:</h4>
          <ul>
            <li>Track your Pain Charges carefully using dice or tokens.</li>
            <li>Coordinate with your party's other healers to ensure you don't sacrifice too much when unnecessary.</li>
            <li>Position yourself centrally to maximize the benefit of your healing auras.</li>
            <li>Remember that some enemies may target you specifically if they recognize your role—be prepared with defensive options.</li>
            <li>Consider carrying emergency healing potions as a last resort to avoid death from your own sacrifices.</li>
          </ul>
        </div>
      </section>

      <section className="guide-section">
        <h3>Sample Combat Round-Flow</h3>
        <p>Here's how a typical combat encounter might play out for a Martyr:</p>
        
        <div className="round-flow">
          <ol>
            <li>
              <strong>Round 1:</strong> Cast Stigmata on yourself, sacrificing 10% of your max HP to create a wound that heals allies for 1d6 HP per round.
              <em>Pain Charges: 2 (Suffering threshold)</em>
            </li>
            <li>
              <strong>Round 2:</strong> Use Blood Sacrifice to heal the party's tank, transferring 15% of your max HP to heal them for 30% of their max HP.
              <em>Pain Charges: 5 (Torment threshold)</em>
            </li>
            <li>
              <strong>Round 3:</strong> Activate Martyr's Blessing, converting 2 Pain Charges into a +2 bonus to all allies' attacks and saves for 3 rounds.
              <em>Pain Charges: 3 (Agony threshold)</em>
            </li>
            <li>
              <strong>Round 4:</strong> An enemy targets your party's mage with a powerful attack. Use Pain Transfer to redirect the damage to yourself, taking 20% of your max HP in damage.
              <em>Pain Charges: 7 (Martyrdom threshold)</em>
            </li>
            <li>
              <strong>Round 5:</strong> With the battle turning desperate, activate Divine Intervention, sacrificing half your remaining HP to prevent any ally from falling below 1 HP for the next 1d4 rounds.
              <em>Pain Charges: 9 (Martyrdom threshold)</em>
            </li>
          </ol>
        </div>

        <p className="conclusion">
          The Martyr thrives on <strong>sacrifice and selflessness</strong>—turning their own suffering into salvation for others.
          Master the balance between sacrifice and survival, and you'll become the beating heart that keeps your party alive through the darkest trials.
        </p>
      </section>
    </div>
  );
};

export default MartyrGuide;
