import React from 'react';
import './ClassGuides.css';

const WitchDoctorGuide = () => {
  return (
    <div className="class-guide">
      <h2>Witch Doctor Guide</h2>
      <p className="class-subtitle">Voodoo Practitioner • Curse Specialist • Spirit Communicator</p>

      <section className="guide-section">
        <h3>Class Overview</h3>
        <p>
          The <strong>Witch Doctor</strong> is a mystical spellcaster who draws power from ancient spirits, voodoo rituals, and curse magic.
          Unlike traditional spellcasters who rely on arcane formulas or divine favor, Witch Doctors form pacts with ancestral spirits
          and loa entities, channeling their power through totems, hexes, and ritual invocations.
        </p>
        <p>
          In a party, Witch Doctors serve as versatile support casters with unique debuffing and battlefield control capabilities.
          Their ability to curse enemies, summon helpful spirits, and deploy totems makes them particularly effective at controlling
          the flow of battle and weakening powerful foes.
        </p>
      </section>

      <section className="guide-section">
        <h3>Unique Mechanic – Voodoo Essence and Invocation Slots</h3>
        <p>
          The Witch Doctor's signature mechanics are Voodoo Essence (VE) and Invocation Slots. Voodoo Essence is a resource that powers
          their abilities, while Invocation Slots determine how many spirits they can channel simultaneously.
        </p>
        
        <div className="mechanic-details">
          <h4>Key Voodoo Concepts:</h4>
          <ul className="mechanic-list">
            <li><strong>Voodoo Essence (VE):</strong> A resource generated by performing rituals, sacrificing items, or drawing power from totems.</li>
            <li><strong>Maximum VE:</strong> You can hold VE equal to your Spirit attribute + your level.</li>
            <li><strong>Spending VE:</strong> VE is spent to cast curses, empower totems, or invoke spirit abilities.</li>
            <li><strong>Invocation Slots:</strong> Determine how many spirits you can channel simultaneously (starts at 2, increases with level).</li>
            <li><strong>Spirit Types:</strong> Different spirits provide different abilities when invoked (healing, damage, protection, etc.).</li>
            <li><strong>Totem Deployment:</strong> Place physical totems on the battlefield that generate VE or provide passive effects.</li>
          </ul>
        </div>

        <div className="ability-table">
          <h4>Sample Spirit Invocations:</h4>
          <table>
            <thead>
              <tr>
                <th>Spirit</th>
                <th>VE Cost</th>
                <th>Effect</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Healing Loa</td>
                <td>3 VE</td>
                <td>Heal an ally for 2d8 HP and cure one status effect</td>
              </tr>
              <tr>
                <td>War Spirit</td>
                <td>2 VE</td>
                <td>Grant an ally +2 to attack rolls and +1d6 damage for 3 rounds</td>
              </tr>
              <tr>
                <td>Vengeance Loa</td>
                <td>4 VE</td>
                <td>Curse an enemy to take 1d6 damage whenever they attack</td>
              </tr>
              <tr>
                <td>Guardian Ancestor</td>
                <td>5 VE</td>
                <td>Create a spectral shield that absorbs 15 damage for an ally</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="note-box">
          <strong>Tactical Tip:</strong> The key to mastering the Witch Doctor is balancing VE generation and consumption while
          strategically choosing which spirits to invoke. Place totems in safe but effective positions, and remember that
          your curses become more powerful when you have personal items from your targets (hair, blood, etc.).
          Always keep at least one Invocation Slot open for emergency situations.
        </p>
      </section>

      <section className="guide-section">
        <h3>Talent Trees</h3>
        <p>
          Witch Doctors have three distinct talent trees that emphasize different aspects of their voodoo powers.
          Each tree offers a unique playstyle and approach to spirit magic.
        </p>

        <div className="talent-tree">
          <h4>1. Curse-Binder</h4>
          <p><em>Focus on hexes, curses, and debilitating effects on enemies.</em></p>
          <ul>
            <li><strong>Hex Master:</strong> Your curses last longer and have enhanced effects.</li>
            <li><strong>Voodoo Doll:</strong> Create a sympathetic link to enemies that amplifies curse damage.</li>
            <li><strong>Curse of Weakness:</strong> Apply debuffs that reduce enemy attributes and resistances.</li>
            <li><strong>Grand Hex (capstone):</strong> Cast a powerful area curse that applies multiple debilitating effects to all enemies within 30 feet for 1d4 rounds.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree is ideal for players who enjoy weakening enemies and controlling the battlefield through debuffs. You'll excel at making powerful foes much less threatening.</p>
        </div>

        <div className="talent-tree">
          <h4>2. Totemic Architect</h4>
          <p><em>Specialize in creating and empowering totems for battlefield control.</em></p>
          <ul>
            <li><strong>Totem Mastery:</strong> Your totems have increased durability and range.</li>
            <li><strong>Multi-Totem:</strong> Deploy multiple totems simultaneously without using additional actions.</li>
            <li><strong>Empowered Fetish:</strong> Enhance totem effects by binding spirits to them.</li>
            <li><strong>Totem Circle (capstone):</strong> Create a circle of five connected totems that generate a powerful combined effect based on the spirits bound to them.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree focuses on battlefield control through strategically placed totems. You'll create zones of influence that can heal allies, harm enemies, or provide various buffs and debuffs.</p>
        </div>

        <div className="talent-tree">
          <h4>3. Loa Chosen</h4>
          <p><em>Emphasize direct communication with powerful spirits and loa entities.</em></p>
          <ul>
            <li><strong>Spirit Speaker:</strong> Communicate with more powerful spirits and gain additional Invocation Slots.</li>
            <li><strong>Loa Pact:</strong> Form a permanent bond with a specific loa that grants unique abilities.</li>
            <li><strong>Spirit Possession:</strong> Allow a spirit to temporarily possess you, granting powerful abilities at the cost of some control.</li>
            <li><strong>Avatar of the Loa (capstone):</strong> Fully channel a powerful loa entity for 1d4 rounds, gaining immense power and access to all of that loa's abilities.</li>
          </ul>
          <p><strong>Playstyle:</strong> This tree is for players who want to form deeper connections with spirits for more direct power. You'll have fewer but more powerful abilities, with the option to temporarily transform through possession.</p>
        </div>
      </section>

      <section className="guide-section">
        <h3>Attribute Priorities</h3>
        <div className="attribute-table">
          <table>
            <thead>
              <tr>
                <th>Attribute</th>
                <th>Importance</th>
                <th>Effect</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Spirit</strong></td>
                <td>Primary</td>
                <td>Increases maximum VE, spirit communication effectiveness, and curse potency</td>
              </tr>
              <tr>
                <td><strong>Wisdom</strong></td>
                <td>Secondary</td>
                <td>Improves your understanding of spirits and resistance to possession</td>
              </tr>
              <tr>
                <td><strong>Constitution</strong></td>
                <td>Secondary</td>
                <td>Provides resilience when channeling powerful spirits</td>
              </tr>
              <tr>
                <td><strong>Charisma</strong></td>
                <td>Tertiary</td>
                <td>Enhances your ability to negotiate with and command spirits</td>
              </tr>
              <tr>
                <td><strong>Dexterity</strong></td>
                <td>Tertiary</td>
                <td>Improves your ability to perform intricate rituals</td>
              </tr>
              <tr>
                <td><strong>Intelligence</strong></td>
                <td>Tertiary</td>
                <td>Helps with understanding complex voodoo rituals and lore</td>
              </tr>
              <tr>
                <td><strong>Strength</strong></td>
                <td>Dump Stat</td>
                <td>Minimal benefit for Witch Doctors</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="guide-section">
        <h3>Core Abilities & Tactics</h3>
        
        <h4>Essential Abilities:</h4>
        <ul className="ability-list">
          <li><strong>Hex:</strong> Apply a basic curse that reduces a target's effectiveness in a specific area.</li>
          <li><strong>Spirit Invocation:</strong> Channel a spirit to gain access to its unique abilities.</li>
          <li><strong>Totem Deployment:</strong> Place a totem on the battlefield that generates an ongoing effect.</li>
          <li><strong>Voodoo Ritual:</strong> Perform a ritual to generate VE or create a specific magical effect.</li>
          <li><strong>Spirit Sight:</strong> See invisible entities and detect spiritual energy.</li>
        </ul>

        <h4>Combat Strategy:</h4>
        <p>The Witch Doctor's approach to combat revolves around preparation and strategic resource management:</p>
        <ol className="round-flow">
          <li><strong>Preparation Phase:</strong> Before combat, perform rituals to generate initial VE and prepare totems.</li>
          <li><strong>Deployment Phase:</strong> Place totems in strategic positions and invoke initial spirits based on the anticipated threat.</li>
          <li><strong>Curse Phase:</strong> Apply hexes and curses to priority targets to reduce their effectiveness.</li>
          <li><strong>Adaptation Phase:</strong> Adjust your spirit invocations and totem placements based on how the battle develops.</li>
        </ol>

        <div className="note-box">
          <h4>Advanced Tactics:</h4>
          <ul>
            <li>Collect personal items from potential enemies when possible to enhance curse effectiveness.</li>
            <li>Remember that totems can be destroyed—place them in protected positions or behind allies.</li>
            <li>Coordinate with party members to maximize the effectiveness of your debuffs and spirit buffs.</li>
            <li>Keep track of your Invocation Slots and which spirits are currently active.</li>
            <li>Some spirits have conflicting personalities—be careful about which ones you invoke simultaneously.</li>
          </ul>
        </div>
      </section>

      <section className="guide-section">
        <h3>Sample Combat Round-Flow</h3>
        <p>Here's how a typical combat encounter might play out for a Witch Doctor:</p>
        
        <div className="round-flow">
          <ol>
            <li>
              <strong>Round 1:</strong> Deploy a Protection Totem near your party's position, generating 2 VE per round and providing a small defensive aura.
              <em>VE: 8, Invocation Slots: 2/2 available</em>
            </li>
            <li>
              <strong>Round 2:</strong> Invoke a War Spirit (2 VE) to buff your party's fighter, granting them bonus damage. The totem generates 2 more VE.
              <em>VE: 8, Invocation Slots: 1/2 available</em>
            </li>
            <li>
              <strong>Round 3:</strong> Cast Hex on the enemy leader (3 VE), reducing their attack bonus and defense. The totem generates 2 more VE.
              <em>VE: 7, Invocation Slots: 1/2 available</em>
            </li>
            <li>
              <strong>Round 4:</strong> Invoke a Vengeance Loa (4 VE) to curse the enemy leader further, causing them to take damage when they attack. The totem generates 2 more VE.
              <em>VE: 5, Invocation Slots: 0/2 available</em>
            </li>
            <li>
              <strong>Round 5:</strong> Your party's rogue is injured. Dismiss the War Spirit to free up an Invocation Slot, then invoke a Healing Loa (3 VE) to heal the rogue. The totem generates 2 more VE.
              <em>VE: 4, Invocation Slots: 0/2 available</em>
            </li>
          </ol>
        </div>

        <p className="conclusion">
          The Witch Doctor thrives on <strong>preparation and spiritual connection</strong>—channeling ancient powers through totems, curses, and spirit invocations.
          Master the flow of Voodoo Essence, and you'll bend both the physical and spiritual worlds to your will.
        </p>
      </section>
    </div>
  );
};

export default WitchDoctorGuide;
